== Forord

https://www.digdir.no/digitalisering-og-samordning/referansekatalogen-it-standarder/1480[_Referansekatalogen_] er en oversikt over obligatoriske og anbefalte IT-standarder i forvaltningen. Obligatoriske standarder skal følges av alle virksomheter. Anbefalte standarder skal følges dersom virksomhetene ikke har en god grunn til å la være å følge dem.

_Referansekatalogen_ skal sikre at innbyggere og næringsliv får tilgang til offentlig informasjon og tjenester på en standardisert måte (uavhengig av brukerutstyr). Den skal også sikre god samhandling mellom offentlige virksomheter, hindre bindinger til bestemte leverandører og sikre god konkurranse i IT-markedet. Katalogen forvaltes av https://www.digdir.no/[Digitaliseringsdirektoratet].

IT-ministeren satte i 2006 ned et bredt sammensatt Standardiseringsråd, som fra 2019 endret sitt navn til https://www.digdir.no/digitalisering-og-samordning/arkitektur-og-standardiseringsradet/1473[Arkitektur- og standardiseringsråd], med medlemmer fra kommunal og statlig sektor. Digitaliseringsdirektoratet får råd fra dette rådet om hvilke standarder som bør være anbefalte eller obligatoriske. Forslag til obligatoriske standarder blir først utredet av Digitaliseringsdirektoratet og deretter oversendt til Kommunal- og moderniseringsdepartementet etter høring. Revidert https://lovdata.no/dokument/SF/forskrift/2013-04-05-959[_Forskrift om IT-standarder i offentlig forvaltning_] med nye obligatoriske standarder legges så fram for Kongen i statsråd som vedtar forskriftsendringer. Digitaliseringsdirektoratet beslutter hva som skal være anbefalte standarder i _Referansekatalogen_, etter utredning og høring i henhold til Arkitektur- og standardiseringsrådets arbeidsmetodikk.

Denne forvaltningsstandarden er utarbeidet av en arbeidsgruppe som er ledet av Språkrådet, i henhold til Arkitektur- og standardiseringsrådets arbeidsmetodikk. Den erstatter https://www.digdir.no/digitale-felleslosninger/standard-begrepskoordinering/1767[den første versjonen fra februar 2013]. Standarden inngår i https://www.digdir.no/digitalisering-og-samordning/begrepsanalyse-og-definisjonsarbeid/1483[bruksområdet «Begrepsanalyse og definisjonsarbeid»] i _Referansekatalogen_. <<vedlegg-d, Vedlegg D>> inneholder de viktigste endringene som er tatt inn etter den første versjonen av standarden.
