== Termer og definisjoner

Dette kapitlet inneholder definisjon av noen av de sentrale begrepene som er brukt i prosessmodellen i denne standarden. Andre begreper som er brukt, kan du finne i https://termbasen.standard.no/[Termbasen] til Standard Norge.

Notasjon som er brukt: Anbefalt term er ført opp i *fet skrift*, eventuell tillatt term i vanlig skrift og rett under anbefalt term, før definisjonen.

=== begrepskoordinering [[begrepskoordinering]][[Begrepskoordinering]]

begrepskoordinering::

terminologiarbeid som omfatter begrepsharmonisering og begrepsdifferensiering

Kilde til definisjon: egendefinert

=== begrepsharmonisering [[begrepsharmonisering]][[Begrepsharmonisering]]

begrepsharmonisering::

terminologiarbeid med formål å etablere en sammenheng mellom to eller flere nært beslektede eller overlappende begreper for å fjerne eller redusere mindre ulikheter mellom dem

Kilde til definisjon: https://standard.no/no/Nettbutikk/produktkatalogen/Produktpresentasjon/?ProductID=1131185[NS-ISO 1087:2019]

Merknad: Gjennom begrepsharmoniseringen skaper vi en felles definisjon og felles term for der det opprinnelig var to eller flere ulike definisjoner og/eller to eller flere ulike termer. Mindre ulikheter som gjenstår, f.eks. uvesentlige kjennetegn, kan reduseres ved at de flyttes til et merknadsfelt, slik at definisjonene er helt like.

=== begrepsdifferensiering [[begrepsdifferensiering]][[Begrepsdifferensiering]]

begrepsdifferensiering::

terminologiarbeid med formål å tydeliggjøre forskjeller mellom nært beslektede eller overlappende begreper som ikke kan harmoniseres

Kilde til definisjon: egendefinert

Merknad: Forskjeller mellom begrepene kan tydeliggjøres i definisjoner, termer, merknader til definisjoner, fagområde og bruksområde.

=== begrepsansvarlig [[begrepsansvarlig]][[Begrepsansvarlig]]

begrepsansvarlig::
begrepseier +
organisasjon eller organisasjonsenhet som er ansvarlig for å forvalte beskrivelsen av et gitt begrep

Kilde til definisjon: egendefinert
