== Vedlegg A (ikke-normativt) - utdypende beskrivelse av stegene i prosessmodell [[vedlegg-a]]

I dette vedlegget utdypes stegene i <<prosessmodell, prosessmodellen>> (figur 1) i den normative delen av standarden.

=== Steg 1: Sammenstilling av begreper [[Steg1]]

==== Hvorfor
For å identifisere likhetene og ulikhetene mellom begrepene som skal harmoniseres eller differensieres, slik at det blir lettere å ta et realistisk valg i neste steg.

==== Forslag til framgangsmåte

. Deltakerne presenterer termene og definisjonene som skal harmoniseres eller differensieres, for hverandre.
. Deltakerne sjekker andre kilder for å se om det finnes andre relevante termer eller definisjoner som er i bruk.
. Dersom begrepene har relasjon til hverandre, tegner deltakerne hver for seg sine egne begrepsdiagrammer. De vurderer også å tegne begrepsdiagrammer fra supplerende kilder om det er mulig.
.. Ved hierarkiske relasjoner er det viktig å ta med inndelingskriterium.
.. Ved assosiative relasjoner er det viktig å ta med en relasjonsbeskrivelse, dvs. hvilken assosiativ relasjon et begrep har til et annet begrep, f.eks. prosess > resultat (saksbehandling > vedtak).
. Deltakerne stiller opp termene og definisjonene med kilder ved siden av hverandre som utgangspunkt for neste steg.
.. Dersom definisjonene inneholder ulike kjennetegn, er det viktig å identifisere hvilke kjennetegn som er vesentlige og hvilke som er uvesentlige eller supplerende.
. Deltakerne identifiserer likheter og ulikheter ved å analysere i hvilken grad begrepene er overlappende, spesielt med tanke på:
* begrepsrelasjoner
** plassering i eventuelle begrepsdiagram
* begrepsdefinisjoner
** vesentlige kjennetegn
* termer
** både anbefalte termer og tillatte termer

==== Tips
Punkt 2::
Nyttige kilder til definisjoner og termer: https://lovdata.no/[Lovdata], https://fellesdatakatalog.digdir.no/concepts[begrepskatalogen], https://snl.no/[Store norske leksikon], https://www.standard.no/toppvalg/termbasen/[Termbasen SNORRE], https://www.uib.no/ub/fagressurser/spesialsamlingene/121707/termportalen[Termportalen] og https://nfm.sdlproducts.com/multiterm[Utenriksdepartementets EU-base] (sistnevnte krever pålogging: brukernavn: guest passord: guest). https://ordbok.uib.no/[_Bokmålsordboka_, _Nynorskordboka_] og https://www.naob.no/[_Det Norske Akademis Ordbok_] finnes også, men disse inneholder hovedsakelig begreper fra allmennspråket.

Det finnes også en rekke sektorspesifikke kilder. En oversikt finnes på https://www.sprakradet.no/Sprakarbeid/Terminologi/termlister-og-termbaser/[Språkrådets nettsider].

Det finnes også internasjonale kilder, f.eks. EUs termbase https://iate.europa.eu/home[IATE] og https://www.iso.org/obp/ui/[ISO Online Browsing Platform (OBP)] eller sektorspesifikke baser som f.eks. http://www.electropedia.org/[Electropedia] for elektroteknikk og https://ec.europa.eu/home-affairs/what-we-do/networks/european_migration_network/glossary_search_en[EMN Glossary] for migrasjon.

Punkt 3::
 Dere kan bruke et vanlig hvitt ark eller et program til å tegne begrepsdiagram. https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/termlosen[_Termlosen_] gir en innføring i begrepsdiagram og inndelingskriterium.

Punkt 4::
 Se også her https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/termlosen[_Termlosen_].


=== Steg 2: Valg mellom begrepsharmonisering og begrepsdifferensiering [[Steg2]]

==== Hvorfor
For å foreta et realistisk valg ved å utrede mulighetene for begrepsharmonisering eller begrepsdifferensiering.

==== Forslag til framgangsmåte

Deltakerne foretar terminologiske og administrative vurderinger ved bl.a. å svare på noen spørsmål, og foretar et realistisk valg for det videre arbeidet.

Jo flere spørsmål knyttet til punkt 1 (under) som blir besvart med “i stor grad”, jo bedre er forutsetningene for begrepsharmonisering.

Jo flere spørsmål knyttet til punkt 1 (under) som blir besvart med “i liten grad”, jo dårligere er forutsetningene for begrepsharmonisering.

1. Følgende spørsmål kan danne grunnlaget for terminologiske vurderinger:

* I hvilken grad tilhører begrepene det samme fagområdet eller overlappende fagområder?
* I hvilken grad er begrepene overlappende (analysert i steg 1)
** I hvilken grad overlapper de vesentlige kjennetegnene i definisjonene hverandre (identifisert i steg 1)?
* I hvilken grad er termene identiske (analysert i steg 1)?
* Dersom virksomhetene har tegnet opp begrepsdiagrammer (i steg 1):
** I hvilken grad overlapper begrepsdiagrammene hverandre?
** I hvilken grad er inndelingskriteriene (ved begreper med hierarkiske begrepsrelasjoner) eller relasjonsbeskrivelsene (ved begreper med assosiative begrepsrelasjoner) identiske eller overlappende?

2. Følgende spørsmål kan danne grunnlaget for administrative vurderinger:

* I hvilken grad får begrepsendringer økonomiske konsekvenser?
* I hvilken grad får begrepsendringer administrative konsekvenser?
* Dersom begrepene har opphav i regelverk (f.eks. lover og forskrifter), offentlige dokumenter eller standarder:
** I hvilken grad er de involverte virksomhetene bundet av begrepsbruken i disse regelverkene og standardene?
** I hvilken grad kan de involverte virksomhetene påvirke regelverkene og andre offentlige dokumenter innenfor en gitt tidsramme? Er det planlagt lov- og forskriftsarbeid eller arbeid med andre offentlige dokumenter av betydning?
** I hvilken grad kan de involverte virksomhetene påvirke standarder innenfor en gitt tidsramme? Er det planlagt nye eller reviderte standarder?
* I hvilken grad har de involverte virksomhetene tilgang til terminologisk kompetanse til å harmonisere eller differensiere begrepene?
* I hvilken grad har de involverte virksomhetene tilgang til faglig kompetanse til å harmonisere eller differensiere begrepene?
* I hvilken grad har de involverte virksomhetene myndighet til å harmonisere eller differensiere begrepene?

3. Realistisk valg:

I noen tilfeller vil det etter vurderingene i punkt 1 og 2 ikke være hensiktsmessig å sette i gang et arbeid med å harmonisere eller differensiere. Det er likevel viktig å dokumentere vurderingene.

Utfallet av vurderingene av hvert enkelt begrep er ett av følgende alternativer for det videre arbeidet:

["upperalpha"]
. Begrepsharmonisering: steg 3
. Begrepsdifferensiering: steg 4
. Verken begrepsharmonisering eller begrepsdifferensiering: slutt


Når det dreier seg om et sett av begreper, kan utfallet være en kombinasjon av alternativene. Noen av begrepene kan harmoniseres, mens andre kan differensieres eller avsluttes uten noe resultat.

==== Tips

Punkt 2::

For statlige virksomheter finnes https://dfo.no/fagomrader/utredningsinstruksen[_Utredningsinstruksen_] som gir føringer for analyse av administrative og økonomiske konsekvenser.

Punkt 3::

Nyttige kilder for å undersøke eventuelle planlagte lovendringer eller nye stortingsmeldinger og NOU-er: https://lovdata.no/[Lovdata.no], https://stortinget.no/no/[Stortinget.no] og https://www.regjeringen.no[Regjeringen.no].

Deltakerne bør ta kontakt med relevante organer om de planlegger å revidere standarder: https://www.standard.no/standarder-pa-horing/[Standard.no], https://www.nek.no/[Nek.no] og https://www.nkom.no/[Nkom.no], https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/forslag-og-utredninger[Digitaliseringsdirektoratet], https://www.cen.eu/Pages/default.aspx[den europeiske standardiseringsorganisasjonen CEN] og https://www.iso.org/home.html[den internasjonale standardiseringsorganisasjonen ISO].

Stoppes arbeidet (alternativ C) fordi begrepene har opphav i lover eller forskrifter, bør deltakerne ta kontakt med ansvarlig departement for å informere om kartleggingen de har gjort, resultatet av den og nytten av å endre lov eller forskrift. Da kan det være mulig å ta hensyn til begrepene ved neste revisjon av den aktuelle loven eller forskriften.

Har begrepene opphav i standarder, bør deltakerne ta kontakt med ansvarlig organ for standarden eller standardene (f.eks. https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/arkitektur-og-standardiseringsradet[Sekretariatet for Arkitektur- og standardiseringsrådet], https://www.standard.no/[Standard Norge], https://www.nek.no/[Norsk Elektroteknisk Komité (NEK)] eller https://www.nkom.no/[Nasjonal Kommunikasjonsmyndighet (Nkom)]) for å informere om kartleggingen de har gjort, resultatet av den og nytten av å endre standarden eller utvikle ny standard.


=== Steg 3: Begrepsharmonisering [[Steg3]]

==== Hvorfor
For å sørge for at deltakerne bruker identiske begreper.

==== Forslag til framgangsmåte
1. Deltakerne vurderer først om noen av de eksisterende definisjonene og termene kan gjenbrukes basert på noen faglige vurderinger:

* Er noen av definisjonene og termene mer faglig korrekte enn andre?
* Er noen av definisjonene og termene mer autoritative enn andre?
** Er noen av definisjonene og termene fastsatte i lover, forskrifter eller standarder?
* Er noen av definisjonene og termene mer i bruk enn andre?
* Er noen av definisjonene og termene mer i tråd med terminologiske prinsipper enn andre?

2. Deltakerne foretar en avveining basert på svarene til punkt 1.

3. Deltakerne tegner et begrepsdiagram dersom begrepene har relasjoner til hverandre. Det er viktig å ta med eksisterende begreper som skal gjenbrukes, i tillegg til nye begreper.

4. Deltakerne utformer definisjoner og fastsette termer for nye, felles begreper.

5. Deltakerne registrerer og tilgjengeliggjør begrepene som virksomhetene blir enige om å harmonisere i en termbase, f.eks. https://fellesdatakatalog.digdir.no/concepts[begrepskatalogen] eller https://www.uib.no/ub/fagressurser/spesialsamlingene/121707/termportalen[Termportalen].

==== Tips

Punkt 3 og 4:: Det finnes en metode for terminologisk arbeid, se https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/termlosen[_Termlosen_].

Om deltakerne blir enige om nye, felles begreper som avviker fra standarder, bør begrepsansvarlig (se <<Steg5, steg 5>>) tar kontakt med ansvarlig organ (f.eks. https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/arkitektur-og-standardiseringsradet[Sekretariatet for Arkitektur- og standardiseringsrådet], https://www.standard.no/[Standard Norge], https://www.nek.no/[Norsk Elektroteknisk Komité (NEK)] eller https://www.nkom.no/[Nasjonal Kommunikasjonsmyndighet (Nkom)]) for å informere om kartleggingen de har gjort, resultatet av den og nytten av endre standarden. Da kan det være mulig å ta hensyn til de nye, felles begrepene ved neste revisjon av den aktuelle standarden.


=== Steg 4: Begrepsdifferensiering [[Steg4]]

==== Hvorfor
For å tydeliggjøre forskjeller mellom begrepene slik at de ikke brukes eller forståes som om de var identiske.

==== Forslag til framgangsmåte
Forskjeller i begrepene kan bli tydeliggjort på en eller flere av følgende måter:

1. Endring i en definisjon:

* Ved å endre ordlyden i definisjonene slik at forskjellene blir tydelige.
2. Endring i term:

* Ved å lage en helt ny term for et eller flere av begrepene
* Ved å legge til et ordledd til en eller flere av termene, f.eks. _godtgjørelse_ > [.underline]#_reise_#_godtgjørelse_
* Ved å legge til et ord eller en ordgruppe til en eller flere av termene, f.eks. _gjennomføringsgrad_ > _gjennomføringsgrad per startkull_

3. Tydeliggjøring i en merknad til definisjonen.

4. Bruk av feltene ‘fagområde’ eller ‘bruksområde’ i den valgte termbasen for å tydeliggjøre ulikhetene.

5. Henvisning mellom de berørte begrepene ved hjelp av relasjoner.

==== Tips
Punkt 1::
 Dersom definisjonene bruker ulike typer kjennetegn, er det en god idé å tydeliggjøre forskjellene ikke bare ved hjelp av endret ordlyd, men også ved å bruke merknadsfeltet.


=== Steg 5: Enighet om forvaltningsmodell [[Steg5]]

==== Hvorfor
For å sikre at de nye begrepene blir forvaltet på en trygg og hensiktsmessig måte.

==== Forslag til framgangsmåte

1. Ved begrepsharmonisering:
Deltakerne blir enige om hvem som skal være ansvarlig for forvaltning av de harmoniserte begrepene. Dersom flere er ansvarlig for ulike deler av begrepssystemet, er det hensiktsmessig å utpeke en hovedansvarlig for det totale begrepssystemet.

2. Ved både begrepsharmonisering og begrepsdifferensiering:
Deltakerne blir enige om varslingsrutiner ved eventuelle endringer eller behov for begrepsendringer.
