name: build adocs

on:
  push:
    branches:
    - master
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build html
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -D docs --backend=html5 -o index.html docs/main.adoc"
    - name: Build pdf
      id: adocbuild_pdf
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor-pdf -D docs -o document.pdf docs/main.adoc"
      continue-on-error: true
    - name: Build epub3
      id: adocbuild_epub3
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor-epub3 -D docs -o document.epub docs/main.adoc"
      continue-on-error: true
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
