name: Build adocs and publish to production

permissions:
  contents: read

on:
  push:
    branches:
      - v2
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/v2'
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v2
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/forvaltningsstandard-begrepskoordinering.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      files: |
        docs/index.html text/html nb
        docs/files/forvaltningsstandard-begrepskoordinering.pdf application/pdf nb files/forvaltningsstandard-begrepskoordinering.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/avlopsvann1.png image/png nb images/avlopsvann1.png
        docs/images/avlopsvann2.png image/png nb images/avlopsvann2.png
        docs/images/forarbeid.png image/png nb images/forarbeid.png
        docs/images/heltidsstudent.png image/png nb images/heltidsstudent.png
        docs/images/prosessmodell.png image/png nb images/prosessmodell.png
      host: https://data.norge.no
      ontology: forvaltningsstandard-begrepskoordinering
      ontology-type: specification
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
